### ISSUE TITLE
upmpdcli | shairport

### ISSUE THREAD

**Issue by H3wastooshort** [vspaceone/spaceinfo#2]
währe ne coole funktion...

**Comment by noppelmax** [comment]
Wozu? Das Ding zeigt Bilder an, warum sollte es Musik streamen?

**Comment by H3wastooshort** [comment]
ein pi weniger

**Comment by noppelmax** [comment]
Ja aber das gehört doch dann nicht in das Repo. Das Repo ist ja nicht für den Pi sondern für das Projekt ;). 
Das sind zwei verschiedene Sachen. Außerdem haben wir 2 Chromecasts im Space liegen

**Comment by H3wastooshort** [comment]
klar 
is aber halt iwi cool

**Comment by noppelmax** [comment]
Naja, mach doch ein eigenes Projekt daraus. Wie habt ihr euch gestern im Plenum bzgl. Audiosystem geeinigt?
